const STORAGE_KEY='inv-mp-v03';
const initial={
 role:'client',clientPage:'home',dkpPage:'queue',orderTab:'overview',
 product:null,employees:120,city:'Москва',fulfilment:'Выездная бригада',procurement:'commercial',search:'',category:'all',
 inn:'',org:false,docs:false,verification:'none',
 quote:{status:'none',version:0,total:0,validUntil:''},
 contract:'none',invoice:'none',payment:'none',roster:'none',
 execution:{status:'none',progress:0},closing:'none',activity:[]
};
const products=[
 {id:'individual',name:'Отдельные исследования',type:'Каталог исследований',category:'individual',desc:'Выберите необходимые лабораторные исследования для сотрудников организации.',icon:'А',availability:'Состав и доступность — по каталогу'},
 {id:'longevity',name:'Пакет «Долголетие»',type:'Готовая программа',category:'package',desc:'Готовая корпоративная программа. Состав и условия отражаются в коммерческом предложении.',icon:'Д',availability:'Индивидуальные условия'},
 {id:'dors',name:'Пакет «ДОРС»',type:'Готовая программа',category:'package',desc:'Готовая корпоративная программа. Состав и условия отражаются в коммерческом предложении.',icon:'Д',availability:'Индивидуальные условия'},
 {id:'hazard',name:'Вредные и опасные производства',type:'Профессиональная программа',category:'production',desc:'Корпоративные лабораторные программы для сотрудников производственных предприятий.',icon:'П',availability:'По параметрам предприятия'}
];
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch(e){return {}}}
function normalize(saved){const s=clone(initial);Object.assign(s,saved||{});s.quote=Object.assign({},initial.quote,(saved||{}).quote||{});s.execution=Object.assign({},initial.execution,(saved||{}).execution||{});s.activity=Array.isArray((saved||{}).activity)?saved.activity:[];return s}
let state=normalize(load());
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){}}
function log(text){state.activity.unshift({time:new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}),text});save()}
function resetDemo(){state=clone(initial);try{localStorage.removeItem(STORAGE_KEY)}catch(e){}render()}
function setRole(role){state.role=role;save();render()}
function go(page){if(state.role==='client')state.clientPage=page;else state.dkpPage=page;save();render()}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function btn(label,fn,kind='primary',disabled=false){return `<button class="btn btn-${kind}" type="button" onclick="${fn}" ${disabled?'disabled':''}>${label}</button>`}
function status(text,kind='gray'){return `<span class="status ${kind}">${text}</span>`}
function money(n){return new Intl.NumberFormat('ru-RU').format(n)+' ₽'}
function selected(){return products.find(x=>x.id===state.product)}
function setValue(key,value){state[key]=value;save();render()}
function setNumber(key,value){state[key]=Math.max(1,Number(value)||1);save()}
function setSearch(value){state.search=value;save()}
function setCategory(value){state.category=value;save();render()}
function submitSearch(){state.clientPage='catalog';save();render()}
function setProduct(id){state.product=id;state.clientPage='configure';log('Выбрана программа: '+selected().name);save();render()}
function demoInn(){state.inn='7701234567';save();render()}
function loadOrg(){if(!state.inn.trim())return;state.org=true;log('Реквизиты организации подтянуты по ИНН — демо');save();render()}
function uploadDocs(){if(!state.org)return;state.docs=true;if(state.verification==='fix')state.verification='none';log('Комплект документов загружен — демо');save();render()}
function sendVerify(){if(!(state.org&&state.docs))return;state.verification='pending';log('Заявка отправлена ДКП на проверку');state.clientPage='order';state.orderTab='overview';save();render()}
function verify(ok){state.verification=ok?'verified':'fix';log(ok?'ДКП подтвердил организацию':'ДКП вернул документы на доработку');save();render()}
function createQuote(){const base=state.product==='individual'?310000:336000;const visit=state.fulfilment==='Выездная бригада'?42000:0;state.quote={status:'sent',version:(state.quote.version||0)+1,total:base+visit,validUntil:'20.08.2026'};log(`ДКП отправил КП v${state.quote.version} — демо`);save();render()}
function acceptQuote(){state.quote.status='accepted';state.contract='ready';log('Клиент принял КП');save();render()}
function requestChange(){state.quote.status='change';log('Клиент запросил корректировку КП');save();render()}
function signContract(){state.contract='signed';state.invoice='issued';log('Договор подтвержден, счет выставлен — демо');save();render()}
function pay(){state.payment='paid';log('Оплата отмечена как полученная — демо');save();render()}
function roster(){state.roster='ready';log(`Список сотрудников принят — ${state.employees} чел.`);save();render()}
function startExec(){state.execution={status:'active',progress:35};log('Заказ передан в существующий контур исполнения INVITRO');save();render()}
function advance(){if(state.execution.status!=='active')return;state.execution.progress=Math.min(100,state.execution.progress+35);if(state.execution.progress>=100){state.execution.progress=100;state.execution.status='done';state.closing='ready';log('Исполнение завершено')}else log('Статус исполнения обновлен');save();render()}
function closeOrder(){state.closing='closed';log('Заказ закрыт документально и финансово — демо');save();render()}
function setOrderTab(tab){state.orderTab=tab;save();render()}

function clientNav(){return [
 ['home','Главная'],['catalog','Каталог'],['organization','Организация'],['order','Мой заказ'],['documents','Документы']
].map(([id,label])=>navBtn(id,label)).join('')}
function dkpNav(){return [
 ['queue','Очередь'],['case','Карточка заказа'],['quotes','КП и документы'],['execution','Исполнение'],['audit','Журнал действий']
].map(([id,label])=>navBtn(id,label)).join('')}
function navBtn(id,label){const cur=state.role==='client'?state.clientPage:state.dkpPage;return `<button class="nav-btn ${cur===id?'active':''}" type="button" onclick="go('${id}')">${label}</button>`}
function mobileNav(){const items=state.role==='client'?[['home','Главная'],['catalog','Каталог'],['order','Заказ'],['organization','Компания']]:[['queue','Очередь'],['case','Заказ'],['execution','Исполнение'],['audit','Журнал']];const cur=state.role==='client'?state.clientPage:state.dkpPage;return items.map(([id,label])=>`<button class="${cur===id?'active':''}" type="button" onclick="go('${id}')">${label}</button>`).join('')}

function home(){return `
 <section class="hero">
  <div class="hero-copy">
   <div class="eyebrow">Лабораторные услуги для организаций</div>
   <h2>Анализы и корпоративные программы в одном цифровом заказе</h2>
   <p>Выберите исследования или готовую программу, оформите организацию и получите коммерческое предложение в личном кабинете.</p>
   <div class="actions">${btn('Выбрать услуги',"go('catalog')")}${state.product?btn('Продолжить заказ',"go('order')",'outline'):''}</div>
  </div>
  <div class="search-panel">
   <div class="search-label">Найти услугу или программу</div>
   <div class="search-row"><input class="search-input" value="${esc(state.search)}" placeholder="Например, Долголетие" oninput="setSearch(this.value)" onkeydown="if(event.key==='Enter')submitSearch()">${btn('Найти','submitSearch()')}</div>
   <div class="quick-links"><button class="quick-chip" onclick="state.search='Долголетие';submitSearch()">Долголетие</button><button class="quick-chip" onclick="state.search='ДОРС';submitSearch()">ДОРС</button><button class="quick-chip" onclick="state.search='производства';submitSearch()">Вредные производства</button></div>
  </div>
 </section>
 <section class="section"><div class="section-head"><div><h2>Корпоративный каталог</h2><div class="section-sub">Выбирайте отдельные исследования и готовые программы для сотрудников организации.</div></div>${btn('Открыть каталог',"go('catalog')",'outline')}</div>${serviceCards(products)}</section>
 <section class="section"><div class="section-head"><div><h2>Как оформить заказ</h2><div class="section-sub">Типовые шаги — в кабинете. Корпоративный менеджер подключается к проверке организации, коммерческому предложению и нестандартным ситуациям.</div></div></div><div class="process-strip"><div class="process-step"><div class="step-num">1</div><b>Выберите услуги</b><span>Пакет, количество сотрудников, город и формат оказания.</span></div><div class="process-step"><div class="step-num">2</div><b>Оформите организацию</b><span>ИНН, реквизиты и документы — в одной карточке.</span></div><div class="process-step"><div class="step-num">3</div><b>Получите КП</b><span>Корпоративный менеджер формирует индивидуальные условия в кабинете.</span></div><div class="process-step"><div class="step-num">4</div><b>Запустите исполнение</b><span>Счет, список сотрудников, офис или выезд и статус заказа.</span></div></div></section>`}
function serviceCards(list){return `<div class="service-grid">${list.map(p=>`<article class="service-card"><div class="service-icon">${p.icon}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="price">По коммерческому предложению</div>${btn('Выбрать',`setProduct('${p.id}')`,'outline')}</article>`).join('')}</div>`}
function catalog(){const q=state.search.trim().toLowerCase();const list=products.filter(p=>{const byText=!q||(p.name+' '+p.type+' '+p.desc).toLowerCase().includes(q);const byCat=state.category==='all'||p.category===state.category;return byText&&byCat});return `
 <div class="card soft" style="margin-bottom:20px"><div class="search-row"><input class="search-input" value="${esc(state.search)}" placeholder="Поиск по каталогу" oninput="setSearch(this.value)" onkeydown="if(event.key==='Enter')render()">${btn('Показать','render()')}</div></div>
 <div class="filters"><button class="filter-chip ${state.category==='all'?'active':''}" onclick="setCategory('all')">Все</button><button class="filter-chip ${state.category==='individual'?'active':''}" onclick="setCategory('individual')">Исследования</button><button class="filter-chip ${state.category==='package'?'active':''}" onclick="setCategory('package')">Готовые программы</button><button class="filter-chip ${state.category==='production'?'active':''}" onclick="setCategory('production')">Производственные программы</button></div>
 ${list.length?`<div class="catalog">${list.map(p=>`<article class="product"><div class="tag">${p.type}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="product-meta"><div class="price">По КП</div><div class="availability">${p.availability}</div></div>${btn('Настроить заказ',`setProduct('${p.id}')`)}</article>`).join('')}</div>`:`<div class="card empty">По вашему запросу ничего не найдено. Очистите поиск или выберите другую категорию.</div>`}`}
function configure(){const p=selected();if(!p)return catalog();return `<div class="grid"><div class="span8"><div class="card"><h2>${p.name}</h2><p class="section-sub">Настройте параметры заказа. Итоговые условия и цена формируются в коммерческом предложении.</p><div class="form-grid"><div class="field"><label>Количество сотрудников</label><input type="number" min="1" value="${state.employees}" oninput="setNumber('employees',this.value)"></div><div class="field"><label>Город исполнения</label><select onchange="setValue('city',this.value)"><option ${state.city==='Москва'?'selected':''}>Москва</option><option ${state.city==='Санкт-Петербург'?'selected':''}>Санкт-Петербург</option><option ${state.city==='Другой регион'?'selected':''}>Другой регион</option></select></div><div class="field"><label>Формат оказания</label><select onchange="setValue('fulfilment',this.value)"><option ${state.fulfilment==='Выездная бригада'?'selected':''}>Выездная бригада</option><option ${state.fulfilment==='В медицинских офисах'?'selected':''}>В медицинских офисах</option></select></div><div class="field"><label>Тип закупки</label><select onchange="setValue('procurement',this.value)"><option value="commercial" ${state.procurement==='commercial'?'selected':''}>Коммерческая закупка</option><option value="regulated" ${state.procurement==='regulated'?'selected':''}>Государственная / регулируемая закупка</option></select></div></div>${state.procurement==='regulated'?`<div class="notice warn">Закупочный маршрут определяется после проверки типа заказчика, источника средств и параметров закупки. Прототип не заменяет ЕИС/ЕАТ и не фиксирует юридическое основание без проверки.</div>`:''}<div class="actions">${btn('Продолжить оформление',"go('organization')")}${btn('Вернуться в каталог',"go('catalog')",'outline')}</div></div></div><aside class="span4"><div class="summary-card"><h3 style="margin-top:0">Ваш заказ</h3><div class="summary-row"><span>Программа</span><b>${p.name}</b></div><div class="summary-row"><span>Сотрудники</span><b>${state.employees}</b></div><div class="summary-row"><span>Город</span><b>${state.city}</b></div><div class="summary-row"><span>Формат</span><b>${state.fulfilment}</b></div><div class="summary-row"><span>Цена</span><b>По КП</b></div></div></aside></div>`}
function organization(){const p=selected();return `<div class="grid"><div class="span7"><div class="card"><h2>Реквизиты организации</h2><div class="field"><label>ИНН</label><input value="${esc(state.inn)}" placeholder="Введите ИНН" oninput="state.inn=this.value;save()"></div><div class="actions">${btn('Подставить демо ИНН','demoInn()','outline')}${btn('Подтянуть реквизиты','loadOrg()','primary',!state.inn)}</div>${state.org?`<div class="divider"></div><div class="summary-row"><span>Организация</span><b>АО «СеверПром»</b></div><div class="summary-row"><span>ИНН</span><b>${esc(state.inn)}</b></div><div class="summary-row"><span>КПП</span><b>770101001 <span class="status info">ДЕМО</span></b></div>`:''}</div><div class="card" style="margin-top:18px"><h2>Документы</h2><p class="section-sub">В рабочей системе набор документов должен зависеть от типа клиента и закупки. Здесь показана только механика единого хранилища.</p><div class="filebox"><div><div class="file-name">Устав / учредительный документ</div><div class="file-meta">${state.docs?'demo_ustav.pdf':'Файл не загружен'}</div></div>${state.docs?status('Получен','ok'):status('Нужен','warn')}</div><div class="filebox"><div><div class="file-name">Полномочия представителя</div><div class="file-meta">${state.docs?'demo_authority.pdf':'Файл не загружен'}</div></div>${state.docs?status('Получен','ok'):status('Нужен','warn')}</div><div class="actions">${btn(state.verification==='fix'?'Загрузить исправленный комплект':'Загрузить демо комплект','uploadDocs()','secondary',!state.org)}</div></div><div class="card" style="margin-top:18px"><h2>Проверка ДКП</h2>${state.verification==='pending'?`<div class="notice blue">Заявка находится на проверке у менеджера ДКП. Все дальнейшие изменения будут видны в статусе заказа.</div>`:state.verification==='verified'?`<div class="notice green">Организация и документы проверены. Менеджер может сформировать коммерческое предложение.</div>`:state.verification==='fix'?`<div class="notice warn">Документы возвращены на доработку. Загрузите исправленный комплект и отправьте заявку повторно.</div><div class="actions">${btn('Отправить повторно','sendVerify()','primary',!state.docs)}</div>`:`${btn('Отправить на проверку ДКП','sendVerify()','primary',!(state.org&&state.docs))}`}</div></div><aside class="span5"><div class="summary-card"><h3 style="margin-top:0">Заказ</h3><div class="summary-row"><span>Программа</span><b>${p?p.name:'Не выбрана'}</b></div><div class="summary-row"><span>Сотрудники</span><b>${state.employees}</b></div><div class="summary-row"><span>Город</span><b>${state.city}</b></div><div class="summary-row"><span>Формат</span><b>${state.fulfilment}</b></div><div class="summary-row"><span>Закупка</span><b>${state.procurement==='regulated'?'Регулируемая':'Коммерческая'}</b></div></div></aside></div>`}
function orderTabs(){return `<div class="order-tabs">${[['overview','Обзор'],['quote','КП'],['employees','Сотрудники'],['execution','Исполнение'],['docs','Документы']].map(([id,l])=>`<button class="order-tab ${state.orderTab===id?'active':''}" onclick="setOrderTab('${id}')">${l}</button>`).join('')}</div>`}
function event(title,done,sub){return `<div class="event ${done?'done':''}"><strong>${title}</strong><small>${sub}</small></div>`}
function order(){const p=selected();if(!p)return `<div class="card empty"><h2>Заказ еще не создан</h2><p>Выберите услуги или корпоративную программу в каталоге.</p><div class="actions" style="justify-content:center">${btn('Перейти в каталог',"go('catalog')")}</div></div>`;return `${orderTabs()}${state.orderTab==='overview'?orderOverview(p):state.orderTab==='quote'?orderQuote():state.orderTab==='employees'?orderEmployees():state.orderTab==='execution'?orderExecution():orderDocuments()}`}
function orderOverview(p){return `<div class="order-layout"><div><div class="card"><h2>Статус заказа</h2><div class="timeline">${event('Организация и документы',state.verification==='verified',state.verification==='verified'?'Проверены ДКП':state.verification==='fix'?'Нужна доработка':'Ожидается проверка')}${event('Коммерческое предложение',['sent','accepted','change'].includes(state.quote.status),state.quote.status==='none'?'Еще не сформировано':state.quote.status==='accepted'?'Принято клиентом':state.quote.status==='change'?'Нужна новая версия':'Отправлено клиенту')}${event('Договор и счет',state.invoice==='issued',state.invoice==='issued'?'Счет выставлен':'После принятия КП')}${event('Оплата',state.payment==='paid',state.payment==='paid'?'Оплата получена — демо':'Ожидается')}${event('Список сотрудников',state.roster==='ready',state.roster==='ready'?`${state.employees} чел. принято`:'После оплаты')}${event('Исполнение',state.execution.status==='done',state.execution.status==='active'?`В работе — ${state.execution.progress}%`:state.execution.status==='done'?'Завершено':'Не запущено')}${event('Закрывающие документы',state.closing==='closed',state.closing==='closed'?'Заказ закрыт':state.closing==='ready'?'Готовы к закрытию':'После исполнения')}</div></div></div><aside><div class="summary-card"><h3 style="margin-top:0">Заказ</h3><div class="summary-row"><span>Программа</span><b>${p?p.name:'Не выбрана'}</b></div><div class="summary-row"><span>Сотрудники</span><b>${state.employees}</b></div><div class="summary-row"><span>Город</span><b>${state.city}</b></div><div class="summary-row"><span>Формат</span><b>${state.fulfilment}</b></div>${state.verification!=='verified'?`<div class="notice blue" style="margin-top:14px">Следующее действие сейчас у ДКП.</div>`:''}</div></aside></div>`}
function orderQuote(){if(state.quote.status==='none')return `<div class="card empty">Коммерческое предложение еще не сформировано. После проверки организации его подготовит менеджер ДКП.</div>`;return `<div class="grid"><div class="span8"><div class="card"><div style="display:flex;justify-content:space-between;gap:16px;align-items:start"><div><div class="eyebrow">Коммерческое предложение</div><h2>КП v${state.quote.version}</h2></div>${state.quote.status==='accepted'?status('Принято','ok'):state.quote.status==='change'?status('На корректировке','warn'):status('На согласовании','info')}</div><div class="divider"></div><div class="summary-row"><span>Лабораторные услуги</span><b>${money(state.quote.total-(state.fulfilment==='Выездная бригада'?42000:0))}</b></div>${state.fulfilment==='Выездная бригада'?`<div class="summary-row"><span>Выездная бригада</span><b>${money(42000)}</b></div>`:''}<div class="divider"></div><div class="quote-total">${money(state.quote.total)}</div><div class="quote-note">Демонстрационная сумма, не прайс INVITRO</div>${state.quote.status==='sent'?`<div class="actions">${btn('Принять КП','acceptQuote()','ok')}${btn('Запросить изменение','requestChange()','outline')}</div>`:''}${state.quote.status==='accepted'&&state.contract!=='signed'?`<div class="actions">${btn('Подтвердить договор','signContract()')}</div>`:''}${state.invoice==='issued'&&state.payment!=='paid'?`<div class="actions">${btn('Отметить демо-оплату','pay()')}</div>`:''}</div></div><aside class="span4"><div class="summary-card"><h3 style="margin-top:0">Статусы</h3><div class="summary-row"><span>КП</span><b>${state.quote.status==='accepted'?'Принято':state.quote.status==='change'?'Корректировка':'Отправлено'}</b></div><div class="summary-row"><span>Договор</span><b>${state.contract==='signed'?'Подписан':state.contract==='ready'?'Готов':'—'}</b></div><div class="summary-row"><span>Счет</span><b>${state.invoice==='issued'?'Выставлен':'—'}</b></div><div class="summary-row"><span>Оплата</span><b>${state.payment==='paid'?'Получена':'—'}</b></div></div></aside></div>`}
function orderEmployees(){return `<div class="grid"><div class="span7"><div class="card"><h2>Список сотрудников</h2><p class="section-sub">В production здесь нужен безопасный roster с валидацией и статусом обработки. В демо реальные персональные данные не используются.</p><div class="filebox"><div><div class="file-name">Список сотрудников</div><div class="file-meta">${state.roster==='ready'?`demo_roster.xlsx • ${state.employees} чел.`:'Файл не загружен'}</div></div>${state.roster==='ready'?status('Принят','ok'):status('Не загружен','gray')}</div><div class="actions">${btn('Загрузить демо список','roster()','primary',state.payment!=='paid'||state.roster==='ready')}</div>${state.payment!=='paid'?`<div class="notice warn" style="margin-top:14px">Загрузка списка доступна после подтверждения оплаты в этом демо-сценарии.</div>`:''}</div></div><aside class="span5"><div class="summary-card"><h3 style="margin-top:0">Готовность</h3><div class="summary-row"><span>Оплата</span><b>${state.payment==='paid'?'Подтверждена':'Ожидается'}</b></div><div class="summary-row"><span>Список</span><b>${state.roster==='ready'?'Принят':'Не готов'}</b></div><div class="summary-row"><span>Формат</span><b>${state.fulfilment}</b></div></div></aside></div>`}
function orderExecution(){return `<div class="grid"><div class="span8"><div class="card"><h2>Исполнение заказа</h2>${state.execution.status==='none'?`<div class="empty">Заказ еще не передан в исполнение.</div>`:`<div class="progress"><div style="width:${state.execution.progress}%"></div></div><div class="section-sub" style="margin-top:10px">Выполнение заказа — ${state.execution.progress}%</div>${state.execution.status==='done'?`<div class="notice green" style="margin-top:18px">Исполнение завершено. Медицинские результаты остаются в существующем контуре INVITRO; marketplace показывает только бизнес-статус.</div>`:''}`}</div></div><aside class="span4"><div class="summary-card"><h3 style="margin-top:0">Действия</h3>${state.roster==='ready'&&state.execution.status==='none'?btn('Передать в исполнение','startExec()'):''}${state.execution.status==='active'?btn('Обновить статус','advance()','secondary'):''}${state.closing==='ready'?`<div style="margin-top:10px">${btn('Закрыть заказ','closeOrder()','ok')}</div>`:''}${state.roster!=='ready'?`<div class="notice blue">Сначала должен быть принят список сотрудников.</div>`:''}</div></aside></div>`}
function orderDocuments(){return documentsTable()}
function documentsTable(){return `<div class="table-wrap"><table class="table"><tr><th>Документ</th><th>Версия</th><th>Статус</th></tr><tr><td>Учредительные документы</td><td>1</td><td>${state.docs?status('Получены','ok'):status('Нет','gray')}</td></tr><tr><td>Коммерческое предложение</td><td>${state.quote.version||'—'}</td><td>${state.quote.status==='accepted'?status('Принято','ok'):state.quote.status==='sent'?status('Отправлено','info'):state.quote.status==='change'?status('Корректировка','warn'):status('Нет','gray')}</td></tr><tr><td>Договор</td><td>1</td><td>${state.contract==='signed'?status('Подписан','ok'):state.contract==='ready'?status('Готов','info'):status('Нет','gray')}</td></tr><tr><td>Счет</td><td>1</td><td>${state.invoice==='issued'?status('Выставлен','ok'):status('Нет','gray')}</td></tr><tr><td>Акт / счет-фактура</td><td>1</td><td>${state.closing==='closed'?status('Закрыто','ok'):state.closing==='ready'?status('Готово','info'):status('Нет','gray')}</td></tr></table></div>`}
function documents(){return `<div class="card"><h2>Документы организации и заказа</h2><p class="section-sub">Единый статус документов вместо разрозненной переписки.</p>${documentsTable()}</div>`}

function queue(){const hasCase=!!state.product||state.verification!=='none'||state.org;return `<div class="kpi-grid"><div class="kpi-card"><div class="kpi">${state.verification==='pending'?1:0}</div><div class="kpi-label">На проверку</div></div><div class="kpi-card"><div class="kpi">${state.quote.status==='change'?1:0}</div><div class="kpi-label">КП на корректировку</div></div><div class="kpi-card"><div class="kpi">${state.execution.status==='active'?1:0}</div><div class="kpi-label">В исполнении</div></div></div><div class="card"><h2>Заявки и исключения</h2>${hasCase?`<div class="table-wrap"><table class="table"><tr><th>Заказчик</th><th>Заказ</th><th>Этап</th><th></th></tr><tr><td><b>АО «СеверПром»</b><div class="help">ИНН ${esc(state.inn||'не указан')}</div></td><td>${selected()?.name||'Без программы'}<div class="help">${state.employees} чел. • ${state.city}</div></td><td>${state.verification==='pending'?status('Проверка организации','warn'):state.verification==='verified'&&state.quote.status==='none'?status('Нужно КП','info'):state.quote.status==='change'?status('Корректировка КП','warn'):state.execution.status==='active'?status('Исполнение','info'):status('В работе','gray')}</td><td>${btn('Открыть',"go('case')",'outline')}</td></tr></table></div>`:`<div class="empty">Новых заявок нет. Пройдите клиентский сценарий и отправьте организацию на проверку.</div>`}</div>`}
function dkpCase(){if(!state.product&&!state.org)return `<div class="card empty">Нет активной заявки. Сначала создайте заказ в клиентском кабинете.</div>`;return `<div class="grid"><div class="span7"><div class="card"><h2>Организация</h2><div class="summary-row"><span>Заказчик</span><b>АО «СеверПром»</b></div><div class="summary-row"><span>ИНН</span><b>${esc(state.inn||'—')}</b></div><div class="summary-row"><span>Документы</span><b>${state.docs?'Получены':'Нет'}</b></div><div class="actions">${state.verification==='pending'?`${btn('Подтвердить организацию','verify(true)','ok')}${btn('Вернуть на доработку','verify(false)','warn')}`:state.verification==='verified'?status('Проверено','ok'):state.verification==='fix'?status('Нужна доработка','warn'):status('Не отправлено','gray')}</div></div></div><aside class="span5"><div class="summary-card"><h3 style="margin-top:0">Потребность</h3><div class="summary-row"><span>Пакет</span><b>${selected()?.name||'—'}</b></div><div class="summary-row"><span>Сотрудники</span><b>${state.employees}</b></div><div class="summary-row"><span>Город</span><b>${state.city}</b></div><div class="summary-row"><span>Формат</span><b>${state.fulfilment}</b></div><div class="summary-row"><span>Закупка</span><b>${state.procurement==='regulated'?'Регулируемая':'Коммерческая'}</b></div></div></aside><div class="span12"><div class="card"><h2>Коммерческое предложение</h2>${state.verification!=='verified'?`<div class="notice blue">Сначала завершите проверку организации.</div>`:state.quote.status==='none'||state.quote.status==='change'?`<p class="section-sub">Коммерческое решение остается у менеджера ДКП. Платформа хранит состав и версии КП.</p>${btn(state.quote.status==='change'?'Создать новую версию КП':'Создать демо КП','createQuote()')}`:`<div style="display:flex;align-items:center;justify-content:space-between;gap:16px"><div><b>КП v${state.quote.version}</b><div class="help">${state.quote.status==='accepted'?'Принято клиентом':'Отправлено клиенту'}</div></div><div class="quote-total">${money(state.quote.total)}</div></div>`}</div></div></div>`}
function quotes(){return `<div class="card"><h2>КП и документы</h2><p class="section-sub">Версии коммерческого предложения и связанные коммерческие документы.</p>${documentsTable()}</div>`}
function execution(){return `<div class="grid"><div class="span6"><div class="card"><h2>Готовность к исполнению</h2><div class="summary-row"><span>Оплата</span><b>${state.payment==='paid'?'Подтверждена':'Нет'}</b></div><div class="summary-row"><span>Список сотрудников</span><b>${state.roster==='ready'?`${state.employees} чел. принято`:'Не готов'}</b></div><div class="summary-row"><span>Формат</span><b>${state.fulfilment}</b></div></div></div><div class="span6"><div class="card"><h2>Execution order</h2>${state.execution.status==='none'?`<div class="empty">Еще не передан.</div>`:`<div class="progress"><div style="width:${state.execution.progress}%"></div></div><div class="section-sub" style="margin-top:10px">${state.execution.status==='done'?'Исполнено':`В работе — ${state.execution.progress}%`}</div>`}</div></div><div class="span12"><div class="card"><h2>Исключения</h2><div class="empty">В демо исключений нет. В рабочем backoffice здесь должны появляться только отклонения: ошибки roster, недоступность выезда, платежные расхождения и другие случаи, требующие вмешательства.</div></div></div></div>`}
function audit(){return `<div class="card"><h2>Журнал действий</h2><p class="section-sub">История ключевых решений по организации и заказу.</p>${state.activity.length?state.activity.map(a=>`<div class="audit-item"><div class="audit-time">${esc(a.time)}</div><div>${esc(a.text)}</div></div>`).join(''):`<div class="empty">Событий пока нет.</div>`}</div>`}

function titleData(){if(state.role==='client'){const map={home:['Корпоративным клиентам','Лабораторные услуги для организаций'],catalog:['Корпоративным клиентам','Каталог услуг'],configure:['Корпоративным клиентам','Параметры заказа'],organization:['Личный кабинет','Организация'],order:['Личный кабинет','Мой заказ'],documents:['Личный кабинет','Документы']};return map[state.clientPage]||map.home}const map={queue:['Рабочее место ДКП','Очередь заявок'],case:['Рабочее место ДКП','Карточка заказа'],quotes:['Рабочее место ДКП','КП и документы'],execution:['Рабочее место ДКП','Исполнение'],audit:['Рабочее место ДКП','Журнал действий']};return map[state.dkpPage]||map.queue}
function pageActions(){if(state.role==='client'&&state.clientPage==='catalog')return btn('Мой заказ',"go('order')",'outline');if(state.role==='dkp'&&state.dkpPage!=='queue')return btn('Вернуться в очередь',"go('queue')",'outline');return ''}
function render(){
 document.getElementById('role-client').classList.toggle('active',state.role==='client');document.getElementById('role-dkp').classList.toggle('active',state.role==='dkp');
 document.getElementById('nav').innerHTML=state.role==='client'?clientNav():dkpNav();document.getElementById('mobile-nav').innerHTML=mobileNav();
 let html='';if(state.role==='client'){if(state.clientPage==='home')html=home();else if(state.clientPage==='catalog')html=catalog();else if(state.clientPage==='configure')html=configure();else if(state.clientPage==='organization')html=organization();else if(state.clientPage==='order')html=order();else html=documents()}else{if(state.dkpPage==='queue')html=queue();else if(state.dkpPage==='case')html=dkpCase();else if(state.dkpPage==='quotes')html=quotes();else if(state.dkpPage==='execution')html=execution();else html=audit()}
 const [kicker,title]=titleData();document.getElementById('org-chip').textContent=state.org?'АО «СеверПром»':'Для организаций';document.getElementById('page-kicker').textContent=kicker;document.getElementById('page-title').textContent=title;document.getElementById('page-actions').innerHTML=pageActions();document.getElementById('content').innerHTML=html;save();
}
render();
