const STORAGE_KEY='inv-mp-v05';
const initial={
 role:'client',clientPage:'home',dkpPage:'queue',orderTab:'overview',
 product:null,cart:[],employees:120,city:'Москва',fulfilment:'Выездная бригада',procurement:'commercial',search:'',category:'all',
 inn:'',org:false,docs:false,verification:'none',
 quote:{status:'none',version:0,total:0,validUntil:''},
 contract:'none',invoice:'none',payment:'none',roster:'none',
 execution:{status:'none',progress:0},closing:'none',activity:[]
};
const products=[
 {id:'longevity',name:'Пакет «Долголетие»',type:'Готовая программа',category:'package',desc:'Корпоративная программа. Состав и условия фиксируются в коммерческом предложении.',icon:'Д',availability:'Индивидуальные условия'},
 {id:'dors',name:'Пакет «ДОРС»',type:'Готовая программа',category:'package',desc:'Корпоративная программа. Состав и условия фиксируются в коммерческом предложении.',icon:'Д',availability:'Индивидуальные условия'},
 {id:'hazard',name:'Вредные и опасные производства',type:'Производственная программа',category:'production',desc:'Подбор лабораторной программы по параметрам предприятия и контингента.',icon:'П',availability:'По параметрам предприятия'},
 {id:'glucose',name:'Глюкоза',type:'Исследование',category:'individual',desc:'Демо-позиция, показывающая механику каталога отдельных лабораторных исследований.',icon:'Г',availability:'Доступность — по корпоративному каталогу'},
 {id:'cbc',name:'Клинический анализ крови',type:'Исследование',category:'individual',desc:'Демо-позиция для сценария добавления отдельных исследований в спецификацию.',icon:'К',availability:'Доступность — по корпоративному каталогу'},
 {id:'tsh',name:'ТТГ',type:'Исследование',category:'individual',desc:'Демо-позиция отдельного исследования. Реальная номенклатура должна поступать из каталога INVITRO.',icon:'Т',availability:'Доступность — по корпоративному каталогу'}
];
const cooperationFormats=[
 {id:'small',title:'Малые закупки',badge:'B2B / B2G',desc:'Выбрать лабораторные услуги, собрать спецификацию, получить КП и пакет документов.',active:true},
 {id:'cobrand',title:'Co-branding / медофис в аптеке',badge:'Партнёрство',desc:'Совместный формат присутствия INVITRO на площадке партнёра.',active:false},
 {id:'franchise',title:'Франчайзинг и инвестиционные проекты',badge:'Развитие сети',desc:'Отдельный маршрут для партнёров и инвесторов.',active:false},
 {id:'outsourcing',title:'Лабораторный аутсорсинг',badge:'B2B',desc:'Передача исследований и специальных лабораторных задач в контур INVITRO.',active:false}
];
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch(e){return {}}}
function normalize(saved){const s=clone(initial);Object.assign(s,saved||{});s.quote=Object.assign({},initial.quote,(saved||{}).quote||{});s.execution=Object.assign({},initial.execution,(saved||{}).execution||{});s.activity=Array.isArray((saved||{}).activity)?saved.activity:[];s.cart=Array.isArray((saved||{}).cart)?saved.cart:[];if(!s.cart.length&&s.product)s.cart=[{id:s.product,qty:1}];return s}
let state=normalize(load());
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){}}
function log(text){state.activity.unshift({time:new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}),text});save()}
function resetDemo(){state=clone(initial);try{localStorage.removeItem(STORAGE_KEY)}catch(e){}render()}
function setRole(role){state.role=role;save();render()}
function go(page){if(state.role==='client')state.clientPage=page;else state.dkpPage=page;save();render()}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function btn(label,fn,kind='primary',disabled=false){return `<button class="btn btn-${kind}" type="button" onclick="${fn}" ${disabled?'disabled':''}>${label}</button>`}
function status(text,kind='gray'){return `<span class="status ${kind}">${text}</span>`}
function money(n){return new Intl.NumberFormat('ru-RU').format(n)+' ₽'}
function productById(id){return products.find(x=>x.id===id)}
function selected(){return productById(state.product)||productById(state.cart[0]?.id)}
function cartCount(){return state.cart.reduce((a,x)=>a+x.qty,0)}
function cartLines(){return state.cart.map(x=>({...x,product:productById(x.id)})).filter(x=>x.product)}
function setValue(key,value){state[key]=value;save();render()}
function setNumber(key,value){state[key]=Math.max(1,Number(value)||1);save()}
function setSearch(value){state.search=value;save()}
function setCategory(value){state.category=value;save();render()}
function submitSearch(){state.clientPage='catalog';save();render()}
function chooseSmallProcurement(){state.role='client';state.clientPage='catalog';save();render()}
function addToCart(id){const found=state.cart.find(x=>x.id===id);if(found)found.qty+=1;else state.cart.push({id,qty:1});state.product=state.cart[0]?.id||id;log('Добавлено в спецификацию: '+productById(id).name);save();render()}
function setProduct(id){addToCart(id);state.clientPage='cart';save();render()}
function removeFromCart(id){state.cart=state.cart.filter(x=>x.id!==id);if(state.product===id)state.product=state.cart[0]?.id||null;save();render()}
function setCartQty(id,value){const row=state.cart.find(x=>x.id===id);if(row){row.qty=Math.max(1,Number(value)||1);save();render()}}
function demoInn(){state.inn='7701234567';save();render()}
function loadOrg(){if(!state.inn.trim())return;state.org=true;log('Реквизиты организации подтянуты по ИНН — демо');save();render()}
function uploadDocs(){if(!state.org)return;state.docs=true;if(state.verification==='fix')state.verification='none';log('Комплект документов загружен — демо');save();render()}
function sendVerify(){if(!(state.org&&state.docs))return;state.verification='pending';log('Заявка отправлена ДКП на проверку');state.clientPage='order';state.orderTab='overview';save();render()}
function verify(ok){state.verification=ok?'verified':'fix';if(!ok)state.docs=false;log(ok?'ДКП подтвердил организацию':'ДКП вернул документы на доработку');save();render()}
function createQuote(){const base=310000;const extra=Math.max(0,state.cart.length-1)*45000;const visit=state.fulfilment==='Выездная бригада'?42000:0;state.quote={status:'sent',version:(state.quote.version||0)+1,total:base+extra+visit,validUntil:'20.08.2026'};log(`ДКП отправил КП v${state.quote.version} — демо`);save();render()}
function acceptQuote(){state.quote.status='accepted';state.contract='ready';log('Клиент принял КП');save();render()}
function requestChange(){state.quote.status='change';log('Клиент запросил корректировку КП');save();render()}
function signContract(){state.contract='signed';state.invoice='issued';log('Договор подтвержден, счет выставлен — демо');save();render()}
function pay(){state.payment='paid';log('Оплата отмечена как полученная — демо');save();render()}
function roster(){state.roster='ready';log(`Список сотрудников принят — ${state.employees} чел.`);save();render()}
function startExec(){state.execution={status:'active',progress:35};log('Заказ передан в существующий контур исполнения INVITRO');save();render()}
function advance(){if(state.execution.status!=='active')return;state.execution.progress=Math.min(100,state.execution.progress+35);if(state.execution.progress>=100){state.execution.progress=100;state.execution.status='done';state.closing='ready';log('Исполнение завершено')}else log('Статус исполнения обновлен');save();render()}
function closeOrder(){state.closing='closed';log('Заказ закрыт документально и финансово — демо');save();render()}
function setOrderTab(tab){state.orderTab=tab;save();render()}
function clientNav(){return [['home','Корпоративным клиентам'],['cooperation','Сотрудничество'],['catalog','Каталог'],['cart',`Спецификация${state.cart.length?' · '+state.cart.length:''}`],['organization','Организация'],['order','Мой заказ']].map(([id,label])=>navBtn(id,label)).join('')}
function dkpNav(){return [['queue','Очередь'],['case','Карточка заказа'],['quotes','КП и документы'],['execution','Исполнение'],['audit','Журнал действий']].map(([id,label])=>navBtn(id,label)).join('')}
function navBtn(id,label){const cur=state.role==='client'?state.clientPage:state.dkpPage;return `<button class="nav-btn ${cur===id?'active':''}" type="button" onclick="go('${id}')">${label}</button>`}
function mobileNav(){const items=state.role==='client'?[['home','Главная'],['cooperation','Форматы'],['catalog','Каталог'],['cart','Заказ']]:[['queue','Очередь'],['case','Заказ'],['execution','Исполнение'],['audit','Журнал']];const cur=state.role==='client'?state.clientPage:state.dkpPage;return items.map(([id,label])=>`<button class="${cur===id?'active':''}" type="button" onclick="go('${id}')">${label}</button>`).join('')}
function home(){return `<section class="hero v05-hero"><div class="hero-copy"><div class="eyebrow">Корпоративным клиентам</div><h2>Форматы сотрудничества с INVITRO</h2><p>Единая точка входа для организаций: от малых закупок лабораторных услуг до партнёрских моделей. В MVP подробно прорабатываем первый сценарий — малые закупки.</p><div class="actions">${btn('Выбрать формат сотрудничества',"go('cooperation')")}${state.cart.length?btn('Продолжить заказ',"go('cart')",'outline'):''}</div></div><div class="v05-hero-panel"><div class="eyebrow">MVP №1</div><h3>Малые закупки</h3><p>Каталог → спецификация → организация → ДКП → КП → договор/счёт → исполнение.</p>${btn('Открыть малые закупки','chooseSmallProcurement()','outline')}</div></section><section class="section"><div class="section-head"><div><h2>Форматы сотрудничества</h2><div class="section-sub">Малые закупки — первый прорабатываемый цифровой сценарий. Остальные направления показаны как верхний уровень корпоративного сайта.</div></div>${btn('Все форматы',"go('cooperation')",'outline')}</div>${cooperationCards()}</section>`}
function cooperationCards(){return `<div class="cooperation-grid">${cooperationFormats.map(x=>`<article class="coop-card ${x.active?'active':''}"><div class="coop-top"><span class="tag">${x.badge}</span>${x.active?status('MVP №1','ok'):status('Концепт','gray')}</div><h3>${x.title}</h3><p>${x.desc}</p>${x.active?btn('Перейти к малым закупкам','chooseSmallProcurement()'):`<button class="btn btn-outline" disabled>Уточняется</button>`}</article>`).join('')}</div>`}
function cooperation(){return `<section class="section section-tight"><div class="section-head"><div><div class="eyebrow">Корпоративным клиентам</div><h2>Выберите формат сотрудничества</h2><div class="section-sub">Малые закупки встроены в общий корпоративный контур и могут использоваться как вход для B2B и B2G.</div></div></div>${cooperationCards()}</section>`}
function catalog(){const q=state.search.trim().toLowerCase();const list=products.filter(p=>{const byText=!q||(p.name+' '+p.type+' '+p.desc).toLowerCase().includes(q);const byCat=state.category==='all'||p.category===state.category;return byText&&byCat});return `<div class="catalog-toolbar card soft"><div><div class="eyebrow">Малые закупки</div><h2>Каталог для организаций</h2><p class="section-sub">Номенклатура исследований ниже показана как демо-механика каталога. Реальный состав и доступность должны поступать из корпоративного каталога INVITRO.</p></div><div class="cart-pill" onclick="go('cart')"><span>Спецификация</span><b>${state.cart.length} поз.</b></div></div><div class="card soft" style="margin-bottom:20px"><div class="search-row"><input class="search-input" value="${esc(state.search)}" placeholder="Найти исследование или программу" oninput="setSearch(this.value)" onkeydown="if(event.key==='Enter')render()">${btn('Показать','render()')}</div></div><div class="filters"><button class="filter-chip ${state.category==='all'?'active':''}" onclick="setCategory('all')">Все</button><button class="filter-chip ${state.category==='package'?'active':''}" onclick="setCategory('package')">Готовые программы</button><button class="filter-chip ${state.category==='production'?'active':''}" onclick="setCategory('production')">Производственные программы</button><button class="filter-chip ${state.category==='individual'?'active':''}" onclick="setCategory('individual')">Исследования</button></div>${list.length?`<div class="catalog">${list.map(catalogCard).join('')}</div>`:`<div class="card empty">По вашему запросу ничего не найдено.</div>`}${state.cart.length?`<div class="sticky-cart"><div><b>В спецификации: ${state.cart.length} позиций</b><span>${cartCount()} ед. выбора</span></div>${btn('Далее: спецификация',"go('cart')")}</div>`:''}`}
function catalogCard(p){const inCart=state.cart.find(x=>x.id===p.id);return `<article class="product"><div class="tag">${p.type}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="product-meta"><div class="price">Цена — по КП</div><div class="availability">${p.availability}</div></div><div class="actions">${btn(inCart?'Добавить ещё':'Добавить в спецификацию',`addToCart('${p.id}')`,inCart?'outline':'primary')}${inCart?status(`В заказе: ${inCart.qty}`,'ok'):''}</div></article>`}
function cart(){const lines=cartLines();if(!lines.length)return `<div class="card empty"><h2>Спецификация пока пустая</h2><p>Добавьте программы или исследования из корпоративного каталога.</p><div class="actions" style="justify-content:center">${btn('Перейти в каталог',"go('catalog')")}</div></div>`;return `<div class="grid"><div class="span8"><div class="card"><div class="section-head"><div><div class="eyebrow">Малые закупки</div><h2>Спецификация заказа</h2><div class="section-sub">Соберите несколько исследований и программ до перехода к параметрам заказа.</div></div></div><div class="spec-list">${lines.map(x=>`<div class="spec-row"><div><b>${x.product.name}</b><div class="help">${x.product.type} · цена по КП</div></div><div class="spec-controls"><input type="number" min="1" value="${x.qty}" onchange="setCartQty('${x.id}',this.value)"><button class="text-button" onclick="removeFromCart('${x.id}')">Удалить</button></div></div>`).join('')}</div><div class="actions">${btn('Далее: параметры',"go('configure')")}${btn('Добавить ещё',"go('catalog')",'outline')}</div></div></div><aside class="span4"><div class="summary-card"><h3 style="margin-top:0">Итого</h3><div class="summary-row"><span>Позиций</span><b>${state.cart.length}</b></div><div class="summary-row"><span>Количество</span><b>${cartCount()}</b></div><div class="summary-row"><span>Стоимость</span><b>По КП</b></div><div class="notice blue" style="margin-top:14px">Корпоративные цены и условия формируются ДКП.</div></div></aside></div>`}
function configure(){if(!state.cart.length)return catalog();return `<div class="grid"><div class="span8"><div class="card"><div class="eyebrow">Шаг после спецификации</div><h2>Параметры заказа</h2><p class="section-sub">Уточните контингент, город, формат оказания и тип закупки.</p><div class="form-grid"><div class="field"><label>Количество сотрудников</label><input type="number" min="1" value="${state.employees}" oninput="setNumber('employees',this.value)"></div><div class="field"><label>Город исполнения</label><select onchange="setValue('city',this.value)"><option ${state.city==='Москва'?'selected':''}>Москва</option><option ${state.city==='Санкт-Петербург'?'selected':''}>Санкт-Петербург</option><option ${state.city==='Другой регион'?'selected':''}>Другой регион</option></select></div><div class="field"><label>Формат оказания</label><select onchange="setValue('fulfilment',this.value)"><option ${state.fulfilment==='Выездная бригада'?'selected':''}>Выездная бригада</option><option ${state.fulfilment==='В медицинских офисах'?'selected':''}>В медицинских офисах</option></select></div><div class="field"><label>Тип закупки</label><select onchange="setValue('procurement',this.value)"><option value="commercial" ${state.procurement==='commercial'?'selected':''}>Коммерческая / прямой маршрут</option><option value="regulated" ${state.procurement==='regulated'?'selected':''}>Государственная / регулируемая закупка</option></select></div></div>${state.procurement==='regulated'?`<div class="notice warn">Гипотеза для валидации: marketplace формирует спецификацию, КП и пакет документов, после чего закупка может переходить во внешний закупочный контур. Конкретный маршрут зависит от статуса заказчика, источника средств и юридической проверки.</div>`:''}<div class="actions">${btn('Далее: организация',"go('organization')")}${btn('Вернуться к спецификации',"go('cart')",'outline')}</div></div></div><aside class="span4"><div class="summary-card"><h3 style="margin-top:0">Спецификация</h3>${cartLines().map(x=>`<div class="summary-row"><span>${x.product.name}</span><b>× ${x.qty}</b></div>`).join('')}<div class="divider"></div><div class="summary-row"><span>Цена</span><b>По КП</b></div></div></aside></div>`}
function organization(){return `<div class="grid"><div class="span7"><div class="card"><h2>Реквизиты организации</h2><div class="field"><label>ИНН</label><input value="${esc(state.inn)}" placeholder="Введите ИНН" oninput="state.inn=this.value;save()"></div><div class="actions">${btn('Подставить демо ИНН','demoInn()','outline')}${btn('Подтянуть реквизиты','loadOrg()','primary',!state.inn)}</div>${state.org?`<div class="divider"></div><div class="summary-row"><span>Организация</span><b>АО «СеверПром»</b></div><div class="summary-row"><span>ИНН</span><b>${esc(state.inn)}</b></div><div class="summary-row"><span>КПП</span><b>770101001 ${status('ДЕМО','info')}</b></div>`:''}</div><div class="card" style="margin-top:18px"><h2>Документы</h2><p class="section-sub">Набор документов в рабочей системе зависит от типа организации и закупочного маршрута.</p><div class="filebox"><div><div class="file-name">Устав / учредительный документ</div><div class="file-meta">${state.docs?'demo_ustav.pdf':'Файл не загружен'}</div></div>${state.docs?status('Получен','ok'):status('Нужен','warn')}</div><div class="filebox"><div><div class="file-name">Полномочия представителя</div><div class="file-meta">${state.docs?'demo_authority.pdf':'Файл не загружен'}</div></div>${state.docs?status('Получен','ok'):status('Нужен','warn')}</div><div class="actions">${btn(state.verification==='fix'?'Загрузить исправленный комплект':'Загрузить демо комплект','uploadDocs()','secondary',!state.org)}</div></div><div class="card" style="margin-top:18px"><h2>Проверка ДКП</h2>${state.verification==='pending'?`<div class="notice blue">Заявка находится на проверке у менеджера ДКП.</div>`:state.verification==='verified'?`<div class="notice green">Организация и документы проверены. Менеджер может сформировать коммерческое предложение.</div>`:state.verification==='fix'?`<div class="notice warn">Документы возвращены на доработку. Загрузите исправленный комплект и отправьте заявку повторно.</div>`:`${btn('Отправить на проверку ДКП','sendVerify()','primary',!(state.org&&state.docs))}`}</div></div><aside class="span5"><div class="summary-card"><h3 style="margin-top:0">Заказ</h3>${cartLines().map(x=>`<div class="summary-row"><span>${x.product.name}</span><b>× ${x.qty}</b></div>`).join('')}<div class="divider"></div><div class="summary-row"><span>Сотрудники</span><b>${state.employees}</b></div><div class="summary-row"><span>Город</span><b>${state.city}</b></div><div class="summary-row"><span>Закупка</span><b>${state.procurement==='regulated'?'Регулируемая':'Прямой маршрут'}</b></div></div></aside></div>`}
function orderTabs(){return `<div class="order-tabs">${[['overview','Обзор'],['quote','КП'],['employees','Сотрудники'],['execution','Исполнение'],['docs','Документы']].map(([id,l])=>`<button class="order-tab ${state.orderTab===id?'active':''}" onclick="setOrderTab('${id}')">${l}</button>`).join('')}</div>`}
function event(title,done,sub){return `<div class="event ${done?'done':''}"><strong>${title}</strong><small>${sub}</small></div>`}
function order(){if(!state.cart.length)return `<div class="card empty"><h2>Заказ еще не создан</h2><p>Соберите спецификацию в каталоге.</p><div class="actions" style="justify-content:center">${btn('Перейти в каталог',"go('catalog')")}</div></div>`;return `${orderTabs()}${state.orderTab==='overview'?orderOverview():state.orderTab==='quote'?orderQuote():state.orderTab==='employees'?orderEmployees():state.orderTab==='execution'?orderExecution():orderDocuments()}`}
function orderOverview(){return `<div class="order-layout"><div><div class="card"><h2>Статус заказа</h2><div class="timeline">${event('Организация и документы',state.verification==='verified',state.verification==='verified'?'Проверены ДКП':state.verification==='fix'?'Нужна доработка':'Ожидается проверка')}${event('Коммерческое предложение',['sent','accepted','change'].includes(state.quote.status),state.quote.status==='none'?'Еще не сформировано':state.quote.status==='accepted'?'Принято клиентом':state.quote.status==='change'?'Нужна новая версия':'Отправлено клиенту')}${event('Договор и счет',state.invoice==='issued',state.invoice==='issued'?'Счет выставлен':'После принятия КП')}${event('Оплата',state.payment==='paid',state.payment==='paid'?'Оплата получена — демо':'Ожидается')}${event('Список сотрудников',state.roster==='ready',state.roster==='ready'?`${state.employees} чел. принято`:'После оплаты')}${event('Исполнение',state.execution.status==='done',state.execution.status==='active'?`В работе — ${state.execution.progress}%`:state.execution.status==='done'?'Завершено':'Не запущено')}${event('Закрывающие документы',state.closing==='closed',state.closing==='closed'?'Заказ закрыт':state.closing==='ready'?'Готовы к закрытию':'После исполнения')}</div></div></div><aside><div class="summary-card"><h3 style="margin-top:0">Спецификация</h3>${cartLines().map(x=>`<div class="summary-row"><span>${x.product.name}</span><b>× ${x.qty}</b></div>`).join('')}</div></aside></div>`}
function orderQuote(){if(state.quote.status==='none')return `<div class="card empty">Коммерческое предложение еще не сформировано. После проверки организации его подготовит менеджер ДКП.</div>`;return `<div class="grid"><div class="span8"><div class="card"><div style="display:flex;justify-content:space-between;gap:16px;align-items:start"><div><div class="eyebrow">Коммерческое предложение</div><h2>КП v${state.quote.version}</h2></div>${state.quote.status==='accepted'?status('Принято','ok'):state.quote.status==='change'?status('На корректировке','warn'):status('На согласовании','info')}</div><div class="divider"></div>${cartLines().map(x=>`<div class="summary-row"><span>${x.product.name} × ${x.qty}</span><b>В составе КП</b></div>`).join('')}<div class="divider"></div><div class="quote-total">${money(state.quote.total)}</div><div class="quote-note">Демонстрационная сумма, не прайс INVITRO</div>${state.quote.status==='sent'?`<div class="actions">${btn('Принять КП','acceptQuote()','ok')}${btn('Запросить изменение','requestChange()','outline')}</div>`:''}${state.quote.status==='accepted'&&state.contract!=='signed'?`<div class="actions">${btn('Подтвердить договор','signContract()')}</div>`:''}${state.invoice==='issued'&&state.payment!=='paid'?`<div class="actions">${btn('Отметить демо-оплату','pay()')}</div>`:''}</div></div><aside class="span4"><div class="summary-card"><h3 style="margin-top:0">Статусы</h3><div class="summary-row"><span>КП</span><b>${state.quote.status==='accepted'?'Принято':state.quote.status==='change'?'Корректировка':'Отправлено'}</b></div><div class="summary-row"><span>Договор</span><b>${state.contract==='signed'?'Подписан':state.contract==='ready'?'Готов':'—'}</b></div><div class="summary-row"><span>Счет</span><b>${state.invoice==='issued'?'Выставлен':'—'}</b></div><div class="summary-row"><span>Оплата</span><b>${state.payment==='paid'?'Получена':'—'}</b></div></div></aside></div>`}
function orderEmployees(){return `<div class="grid"><div class="span7"><div class="card"><h2>Список сотрудников</h2><p class="section-sub">В production здесь нужен безопасный roster с валидацией. В демо реальные персональные данные не используются.</p><div class="filebox"><div><div class="file-name">Список сотрудников</div><div class="file-meta">${state.roster==='ready'?`demo_roster.xlsx • ${state.employees} чел.`:'Файл не загружен'}</div></div>${state.roster==='ready'?status('Принят','ok'):status('Не загружен','gray')}</div><div class="actions">${btn('Загрузить демо список','roster()','primary',state.payment!=='paid'||state.roster==='ready')}</div>${state.payment!=='paid'?`<div class="notice warn" style="margin-top:14px">Загрузка списка доступна после подтверждения оплаты.</div>`:''}</div></div><aside class="span5"><div class="summary-card"><h3 style="margin-top:0">Готовность</h3><div class="summary-row"><span>Оплата</span><b>${state.payment==='paid'?'Подтверждена':'Ожидается'}</b></div><div class="summary-row"><span>Список</span><b>${state.roster==='ready'?'Принят':'Не готов'}</b></div></div></aside></div>`}
function orderExecution(){return `<div class="grid"><div class="span8"><div class="card"><h2>Исполнение заказа</h2>${state.execution.status==='none'?`<div class="empty">Заказ еще не передан в исполнение.</div>`:`<div class="progress"><div style="width:${state.execution.progress}%"></div></div><div class="section-sub" style="margin-top:10px">Выполнение заказа — ${state.execution.progress}%</div>${state.execution.status==='done'?`<div class="notice green" style="margin-top:18px">Исполнение завершено. Медицинские результаты остаются в существующем контуре INVITRO; marketplace показывает бизнес-статус.</div>`:''}`}</div></div><aside class="span4"><div class="summary-card"><h3 style="margin-top:0">Действия</h3>${state.roster==='ready'&&state.execution.status==='none'?btn('Передать в исполнение','startExec()'):''}${state.execution.status==='active'?btn('Обновить статус','advance()','secondary'):''}${state.closing==='ready'?`<div style="margin-top:10px">${btn('Закрыть заказ','closeOrder()','ok')}</div>`:''}</div></aside></div>`}
function orderDocuments(){return documentsTable()}
function documentsTable(){return `<div class="table-wrap"><table class="table"><tr><th>Документ</th><th>Версия</th><th>Статус</th></tr><tr><td>Учредительные документы</td><td>1</td><td>${state.docs?status('Получены','ok'):status('Нет','gray')}</td></tr><tr><td>Коммерческое предложение</td><td>${state.quote.version||'—'}</td><td>${state.quote.status==='accepted'?status('Принято','ok'):state.quote.status==='sent'?status('Отправлено','info'):state.quote.status==='change'?status('Корректировка','warn'):status('Нет','gray')}</td></tr><tr><td>Договор</td><td>1</td><td>${state.contract==='signed'?status('Подписан','ok'):state.contract==='ready'?status('Готов','info'):status('Нет','gray')}</td></tr><tr><td>Счет</td><td>1</td><td>${state.invoice==='issued'?status('Выставлен','ok'):status('Нет','gray')}</td></tr><tr><td>Акт / счет-фактура</td><td>1</td><td>${state.closing==='closed'?status('Закрыто','ok'):state.closing==='ready'?status('Готово','info'):status('Нет','gray')}</td></tr></table></div>`}
function documents(){return `<div class="card"><h2>Документы организации и заказа</h2>${documentsTable()}</div>`}
function queue(){const hasCase=state.cart.length>0||state.verification!=='none'||state.org;return `<div class="kpi-grid"><div class="kpi-card"><div class="kpi">${state.verification==='pending'?1:0}</div><div class="kpi-label">На проверку</div></div><div class="kpi-card"><div class="kpi">${state.quote.status==='change'?1:0}</div><div class="kpi-label">КП на корректировку</div></div><div class="kpi-card"><div class="kpi">${state.execution.status==='active'?1:0}</div><div class="kpi-label">В исполнении</div></div></div><div class="card"><h2>Заявки и исключения</h2>${hasCase?`<div class="table-wrap"><table class="table"><tr><th>Заказчик</th><th>Потребность</th><th>Этап</th><th></th></tr><tr><td><b>АО «СеверПром»</b><div class="help">ИНН ${esc(state.inn||'не указан')}</div></td><td>${state.cart.length} позиций<div class="help">${state.employees} чел. • ${state.city}</div></td><td>${state.verification==='pending'?status('Проверка организации','warn'):state.verification==='verified'&&state.quote.status==='none'?status('Нужно КП','info'):state.quote.status==='change'?status('Корректировка КП','warn'):state.execution.status==='active'?status('Исполнение','info'):status('В работе','gray')}</td><td>${btn('Открыть',"go('case')",'outline')}</td></tr></table></div>`:`<div class="empty">Новых заявок нет. Клиент должен собрать спецификацию и отправить организацию на проверку.</div>`}</div>`}
function dkpCase(){if(!state.cart.length&&!state.org)return `<div class="card empty">Нет активной заявки. Сначала создайте заказ в клиентском кабинете.</div>`;return `<div class="grid"><div class="span7"><div class="card"><h2>Организация</h2><div class="summary-row"><span>Заказчик</span><b>АО «СеверПром»</b></div><div class="summary-row"><span>ИНН</span><b>${esc(state.inn||'—')}</b></div><div class="summary-row"><span>Документы</span><b>${state.docs?'Получены':'Нет'}</b></div><div class="actions">${state.verification==='pending'?`${btn('Подтвердить организацию','verify(true)','ok')}${btn('Вернуть на доработку','verify(false)','warn')}`:state.verification==='verified'?status('Проверено','ok'):state.verification==='fix'?status('Нужна доработка','warn'):status('Не отправлено','gray')}</div></div></div><aside class="span5"><div class="summary-card"><h3 style="margin-top:0">Потребность</h3>${cartLines().map(x=>`<div class="summary-row"><span>${x.product.name}</span><b>× ${x.qty}</b></div>`).join('')}<div class="divider"></div><div class="summary-row"><span>Сотрудники</span><b>${state.employees}</b></div><div class="summary-row"><span>Город</span><b>${state.city}</b></div><div class="summary-row"><span>Закупка</span><b>${state.procurement==='regulated'?'Регулируемая':'Прямой маршрут'}</b></div></div></aside><div class="span12"><div class="card"><h2>Коммерческое предложение</h2>${state.verification!=='verified'?`<div class="notice blue">Сначала завершите проверку организации.</div>`:state.quote.status==='none'||state.quote.status==='change'?`<p class="section-sub">ДКП формирует индивидуальные условия. Платформа хранит состав спецификации и версии КП.</p>${btn(state.quote.status==='change'?'Создать новую версию КП':'Создать демо КП','createQuote()')}`:`<div style="display:flex;align-items:center;justify-content:space-between;gap:16px"><div><b>КП v${state.quote.version}</b><div class="help">${state.quote.status==='accepted'?'Принято клиентом':'Отправлено клиенту'}</div></div><div class="quote-total">${money(state.quote.total)}</div></div>`}</div></div></div>`}
function quotes(){return `<div class="card"><h2>КП и документы</h2>${documentsTable()}</div>`}
function execution(){return `<div class="grid"><div class="span6"><div class="card"><h2>Готовность к исполнению</h2><div class="summary-row"><span>Оплата</span><b>${state.payment==='paid'?'Подтверждена':'Нет'}</b></div><div class="summary-row"><span>Список сотрудников</span><b>${state.roster==='ready'?`${state.employees} чел. принято`:'Не готов'}</b></div></div></div><div class="span6"><div class="card"><h2>Исполнение</h2>${state.execution.status==='none'?`<div class="empty">Еще не передан.</div>`:`<div class="progress"><div style="width:${state.execution.progress}%"></div></div><div class="section-sub" style="margin-top:10px">${state.execution.status==='done'?'Исполнено':`В работе — ${state.execution.progress}%`}</div>`}</div></div></div>`}
function audit(){return `<div class="card"><h2>Журнал действий</h2>${state.activity.length?state.activity.map(a=>`<div class="audit-item"><div class="audit-time">${esc(a.time)}</div><div>${esc(a.text)}</div></div>`).join(''):`<div class="empty">Событий пока нет.</div>`}</div>`}
function titleData(){if(state.role==='client'){const map={home:['Корпоративным клиентам','Решения для организаций'],cooperation:['Корпоративным клиентам','Форматы сотрудничества'],catalog:['Малые закупки','Каталог для организаций'],cart:['Малые закупки','Спецификация заказа'],configure:['Малые закупки','Параметры заказа'],organization:['Личный кабинет','Организация'],order:['Личный кабинет','Мой заказ'],documents:['Личный кабинет','Документы']};return map[state.clientPage]||map.home}const map={queue:['Рабочее место ДКП','Очередь заявок'],case:['Рабочее место ДКП','Карточка заказа'],quotes:['Рабочее место ДКП','КП и документы'],execution:['Рабочее место ДКП','Исполнение'],audit:['Рабочее место ДКП','Журнал действий']};return map[state.dkpPage]||map.queue}
function pageActions(){if(state.role==='client'&&state.clientPage==='catalog')return btn(`Спецификация · ${state.cart.length}`,"go('cart')",'outline');if(state.role==='dkp'&&state.dkpPage!=='queue')return btn('Вернуться в очередь',"go('queue')",'outline');return ''}
function render(){document.getElementById('role-client').classList.toggle('active',state.role==='client');document.getElementById('role-dkp').classList.toggle('active',state.role==='dkp');document.getElementById('nav').innerHTML=state.role==='client'?clientNav():dkpNav();document.getElementById('mobile-nav').innerHTML=mobileNav();let html='';if(state.role==='client'){if(state.clientPage==='home')html=home();else if(state.clientPage==='cooperation')html=cooperation();else if(state.clientPage==='catalog')html=catalog();else if(state.clientPage==='cart')html=cart();else if(state.clientPage==='configure')html=configure();else if(state.clientPage==='organization')html=organization();else if(state.clientPage==='order')html=order();else html=documents()}else{if(state.dkpPage==='queue')html=queue();else if(state.dkpPage==='case')html=dkpCase();else if(state.dkpPage==='quotes')html=quotes();else if(state.dkpPage==='execution')html=execution();else html=audit()}const [kicker,title]=titleData();document.getElementById('org-chip').textContent=state.org?'АО «СеверПром»':'Для организаций';document.getElementById('page-kicker').textContent=kicker;document.getElementById('page-title').textContent=title;document.getElementById('page-actions').innerHTML=pageActions();document.getElementById('content').innerHTML=html;save()}
render();