const initial={role:'client',clientPage:'home',dkpPage:'queue',product:null,employees:120,city:'Москва',fulfilment:'Выездная бригада',inn:'',org:false,docs:false,verification:'none',quote:{status:'none',version:0,total:0},contract:'none',invoice:'none',payment:'none',roster:'none',execution:{status:'none',progress:0},closing:'none',activity:[]};
let state={...initial,...load()};
const products=[
{id:'longevity',name:'Пакет «Долголетие»',type:'Готовая программа',desc:'Демонстрационная карточка. Точный состав должен поступать из реального каталога INVITRO.'},
{id:'dors',name:'Пакет «ДОРС»',type:'Готовая программа',desc:'Рабочее название из материалов Ирины. Точный состав пока не подтвержден.'},
{id:'hazard',name:'Вредные / опасные производства',type:'Профессиональная программа',desc:'Корпоративная программа для сотрудников производств. Состав требует каталожной и юридической проверки.'}
];
function load(){try{return JSON.parse(localStorage.getItem('inv-mp')||'{}')}catch(e){return {}}}
function save(){try{localStorage.setItem('inv-mp',JSON.stringify(state))}catch(e){}}
function log(t){state.activity.unshift({time:new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}),text:t});save()}
function resetDemo(){state=JSON.parse(JSON.stringify(initial));try{localStorage.removeItem('inv-mp')}catch(e){}render()}
function setRole(r){state.role=r;save();render()}
function go(p){if(state.role==='client')state.clientPage=p;else state.dkpPage=p;save();render()}
function btn(label,fn,kind='primary',disabled=false){return `<button class="btn btn-${kind}" onclick="${fn}" ${disabled?'disabled':''}>${label}</button>`}
function status(t,c='gray'){return `<span class="status ${c}">${t}</span>`}
function money(n){return new Intl.NumberFormat('ru-RU').format(n)+' ₽'}
function selected(){return products.find(x=>x.id===state.product)}
function nav(){
 if(state.role==='client')return `<div class="nav-title">Клиентский кабинет</div>${navBtn('home','Главная','корпоративные услуги')}${navBtn('catalog','Каталог','услуги и программы')}${navBtn('organization','Организация','реквизиты и документы')}${navBtn('order','Мой заказ','КП, оплата, исполнение')}${navBtn('documents','Документы','договор, счет, акты')}`;
 return `<div class="nav-title">Backoffice ДКП</div>${navBtn('queue','Очередь','заявки и исключения')}${navBtn('case','Карточка заказа','верификация и КП')}${navBtn('quotes','КП и документы','версии и статусы')}${navBtn('execution','Исполнение','handoff и исключения')}${navBtn('audit','Журнал действий','audit trail')}`;
}
function navBtn(id,title,sub){const cur=state.role==='client'?state.clientPage:state.dkpPage;return `<button class="nav-btn ${cur===id?'active':''}" onclick="go('${id}')">${title}<small>${sub}</small></button>`}
function setProduct(id){state.product=id;state.clientPage='organization';log('Выбран продукт: '+selected().name);save();render()}
function demoInn(){state.inn='7701234567';save();render()}
function loadOrg(){if(!state.inn)return;state.org=true;log('Реквизиты организации подтянуты по ИНН - демо');save();render()}
function uploadDocs(){if(!state.org)return;state.docs=true;log('Учредительные документы загружены - демо');save();render()}
function sendVerify(){if(!(state.org&&state.docs))return;state.verification='pending';log('Заявка отправлена ДКП на верификацию');state.clientPage='order';save();render()}
function verify(ok){state.verification=ok?'verified':'fix';log(ok?'ДКП подтвердил организацию':'ДКП вернул документы на доработку');save();render()}
function createQuote(){state.quote={status:'sent',version:state.quote.version+1,total:378000};log('ДКП отправил КП v'+state.quote.version+' - демо');save();render()}
function acceptQuote(){state.quote.status='accepted';state.contract='ready';log('Клиент принял КП');save();render()}
function requestChange(){state.quote.status='change';log('Клиент запросил изменение КП');save();render()}
function signContract(){state.contract='signed';state.invoice='issued';log('Договор подтвержден, счет выставлен - демо');save();render()}
function pay(){state.payment='paid';log('Оплата получена - демо');save();render()}
function roster(){state.roster='ready';log('Список сотрудников принят - '+state.employees+' чел.');save();render()}
function startExec(){state.execution={status:'active',progress:35};log('Заказ передан в существующий контур исполнения');save();render()}
function advance(){state.execution.progress=Math.min(100,state.execution.progress+35);if(state.execution.progress===100){state.execution.status='done';state.closing='ready';log('Исполнение завершено')}else log('Статус исполнения обновлен');save();render()}
function closeOrder(){state.closing='closed';log('Заказ закрыт документально и финансово');save();render()}
function home(){return `<div class="hero"><div class="hero-kicker">INVITRO • корпоративные лабораторные услуги</div><h1>Заказ лабораторных программ для организаций в одном цифровом процессе</h1><p>Выберите услуги INVITRO, зарегистрируйте организацию, передайте документы, получите коммерческое предложение и отслеживайте заказ без разрозненной переписки.</p><div class="hero-actions">${btn('Перейти в каталог',"go('catalog')")}${state.product?btn('Продолжить заказ',"go('order')",'outline'):''}</div></div><div class="grid"><div class="card brand-card span4"><div class="kpi">1</div><div class="kpi-label">единая карточка организации и заказа</div></div><div class="card brand-card span4"><div class="kpi">2</div><div class="kpi-label">связанных интерфейса: клиент и ДКП</div></div><div class="card brand-card span4"><div class="kpi">MVP</div><div class="kpi-label">только собственные услуги INVITRO</div></div><div class="card span12"><h2>Как проходит заказ</h2><div class="process"><div class="process-item"><div class="num">1</div><h3>Выберите программу</h3><p class="sub">Пакет, количество сотрудников, город и офис/выезд.</p></div><div class="process-item"><div class="num">2</div><h3>Оформите организацию</h3><p class="sub">ИНН, реквизиты и документы переходят на проверку менеджеру ДКП.</p></div><div class="process-item"><div class="num">3</div><h3>Получите КП и запустите исполнение</h3><p class="sub">КП, договор, счет, список сотрудников, статус и закрывающие документы.</p></div></div></div></div>`}
function catalog(){return `<h1>Каталог корпоративных программ</h1><p class="sub">MVP №1 - только собственные услуги INVITRO. Реальные медицинские составы и цены в демо не выдумываются.</p><div class="catalog">${products.map(p=>`<div class="product"><span class="tag">${p.type}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="price">По КП<small>Индивидуальные условия формирует ДКП</small></div>${btn('Настроить заказ',`setProduct('${p.id}')`)}</div>`).join('')}</div>`}
function organization(){return `<h1>Организация и документы</h1><p class="sub">Целевая логика: ИНН → реквизиты → документы → верификация ДКП.</p><div class="grid"><div class="card span6"><h2>1. Организация</h2><div class="field"><label>ИНН</label><input value="${state.inn}" oninput="state.inn=this.value;save()"></div><div class="actions">${btn('Подставить демо ИНН','demoInn()','outline')}${btn('Подтянуть реквизиты','loadOrg()')}</div>${state.org?`<div class="divider"></div><table class="table"><tr><td>Юридическое наименование</td><td><b>АО «СеверПром»</b></td></tr><tr><td>ИНН</td><td>${state.inn}</td></tr><tr><td>КПП</td><td>770101001 ${status('ДЕМО','info')}</td></tr></table>`:''}</div><div class="card span6"><h2>2. Документы</h2><div class="filebox"><b>Устав / учредительный документ</b>${state.docs?status('Получен','ok'):status('Нужен','warn')}</div><div class="filebox"><b>Полномочия представителя</b>${state.docs?status('Получен','ok'):status('Нужен','warn')}</div><div class="actions">${btn('Загрузить демо комплект','uploadDocs()','secondary',!state.org)}</div></div><div class="card span12"><h2>3. Верификация ДКП</h2>${state.verification==='pending'?`<div class="notice blue"><b>Заявка в очереди ДКП.</b> Клиент видит единый статус вместо переписки.</div>`:state.verification==='verified'?`<div class="notice"><b>Организация подтверждена.</b> ДКП может формировать КП.</div>`:state.verification==='fix'?`<div class="notice warn"><b>Документы требуют доработки.</b></div>`:btn('Отправить на верификацию ДКП','sendVerify()','primary',!(state.org&&state.docs))}</div></div>`}
function order(){return `<h1>Мой заказ ${state.closing==='closed'?status('Закрыт','ok'):status('В работе','info')}</h1><p class="sub">${selected()?.name||'Программа не выбрана'} • ${state.employees} сотрудников • ${state.city} • ${state.fulfilment}</p><div class="grid"><div class="card span8"><h2>Статус</h2><div class="timeline">${event('Организация и документы',state.verification==='verified',state.verification==='verified'?'Проверены ДКП':'Ожидается проверка')}${event('Коммерческое предложение',['sent','accepted','change'].includes(state.quote.status),state.quote.status==='none'?'Еще не сформировано':state.quote.status==='accepted'?'Принято':'Отправлено / корректировка')}${event('Договор и счет',state.invoice==='issued',state.invoice==='issued'?'Счет выставлен':'После принятия КП')}${event('Оплата',state.payment==='paid',state.payment==='paid'?'Получена - демо':'Ожидается')}${event('Список сотрудников',state.roster==='ready',state.roster==='ready'?'Принят':'После оплаты')}${event('Исполнение',state.execution.status==='done',state.execution.status==='active'?'В работе '+state.execution.progress+'%':state.execution.status==='done'?'Завершено':'Не запущено')}${event('Закрывающие документы',state.closing==='closed',state.closing==='closed'?'Заказ закрыт':state.closing==='ready'?'Готовы':'После исполнения')}</div></div><div class="card span4"><h3>Действия</h3>${state.verification!=='verified'?`<div class="mutedbox">Следующий шаг сейчас у ДКП.</div>`:''}${state.quote.status==='sent'?btn('Принять КП','acceptQuote()','ok')+' '+btn('Запросить изменение','requestChange()','outline'):''}${state.quote.status==='accepted'&&state.contract!=='signed'?btn('Подтвердить договор','signContract()'):''}${state.invoice==='issued'&&state.payment!=='paid'?btn('Отметить демо-оплату','pay()'):''}${state.payment==='paid'&&state.roster!=='ready'?btn('Загрузить список','roster()'):''}${state.roster==='ready'&&state.execution.status==='none'?btn('Передать в исполнение','startExec()'):''}${state.execution.status==='active'?btn('Обновить статус','advance()','secondary'):''}${state.closing==='ready'?btn('Закрыть заказ','closeOrder()','ok'):''}</div>${state.quote.status!=='none'?`<div class="card span12"><h2>КП v${state.quote.version}</h2><div class="kpi">${money(state.quote.total)}</div><div class="help">ДЕМО - не прайс INVITRO</div></div>`:''}${state.execution.status!=='none'?`<div class="card span12"><h2>Исполнение</h2><div class="progress"><div style="width:${state.execution.progress}%"></div></div><div class="help">Агрегированный бизнес-статус. Медицинские результаты остаются в существующем контуре INVITRO.</div></div>`:''}</div>`}
function event(title,done,sub){return `<div class="event ${done?'done':''}"><strong>${title}</strong><small>${sub}</small></div>`}
function documents(){return `<h1>Документы заказа</h1><p class="sub">Документы привязаны к организации и заказу, имеют версии и статусы.</p><div class="card"><table class="table"><tr><th>Документ</th><th>Статус</th></tr><tr><td>Учредительные документы</td><td>${state.docs?status('Получены','ok'):status('Нет')}</td></tr><tr><td>КП</td><td>${state.quote.status==='accepted'?status('Принято','ok'):state.quote.status==='sent'?status('Отправлено','info'):status('Нет')}</td></tr><tr><td>Договор</td><td>${state.contract==='signed'?status('Подписан','ok'):status('Нет')}</td></tr><tr><td>Счет</td><td>${state.invoice==='issued'?status('Выставлен','ok'):status('Нет')}</td></tr><tr><td>Акт / счет-фактура</td><td>${state.closing==='closed'?status('Закрыто','ok'):status('Нет')}</td></tr></table></div>`}
function queue(){return `<h1>Очередь ДКП</h1><p class="sub">Менеджер работает с новыми заявками и исключениями, а не контролирует каждый типовой шаг вручную.</p><div class="grid"><div class="card brand-card span4"><div class="kpi">${state.verification==='pending'?1:0}</div><div class="kpi-label">на верификацию</div></div><div class="card brand-card span4"><div class="kpi">${state.quote.status==='change'?1:0}</div><div class="kpi-label">КП на корректировку</div></div><div class="card brand-card span4"><div class="kpi">${state.execution.status==='active'?1:0}</div><div class="kpi-label">в исполнении</div></div><div class="card span12"><table class="table"><tr><th>Заказчик</th><th>Заказ</th><th>Этап</th><th></th></tr><tr><td><b>АО «СеверПром»</b></td><td>${selected()?.name||'-'} • ${state.employees} чел.</td><td>${state.verification==='pending'?status('Верификация','warn'):state.verification==='verified'&&state.quote.status==='none'?status('Нужно КП','info'):state.quote.status==='change'?status('Корректировка КП','warn'):status('В работе','gray')}</td><td>${btn('Открыть',"go('case')",'outline')}</td></tr></table></div></div>`}
function dkpCase(){return `<h1>Карточка заказа - ДКП</h1><p class="sub">Единый объект вместо цепочки писем: организация, документы, КП, договор, оплата и исполнение.</p><div class="grid"><div class="card span6"><h2>Организация</h2><table class="table"><tr><td>Заказчик</td><td><b>АО «СеверПром»</b></td></tr><tr><td>ИНН</td><td>${state.inn||'-'}</td></tr><tr><td>Документы</td><td>${state.docs?status('Получены','ok'):status('Нет','warn')}</td></tr></table><div class="actions">${state.verification==='pending'?btn('Подтвердить','verify(true)','ok')+' '+btn('Вернуть','verify(false)','warn'):state.verification==='verified'?status('Проверено','ok'):''}</div></div><div class="card span6"><h2>Потребность</h2><table class="table"><tr><td>Пакет</td><td>${selected()?.name||'-'}</td></tr><tr><td>Сотрудники</td><td>${state.employees}</td></tr><tr><td>Город</td><td>${state.city}</td></tr><tr><td>Формат</td><td>${state.fulfilment}</td></tr></table></div><div class="card span12"><h2>Коммерческое предложение</h2>${state.verification!=='verified'?`<div class="mutedbox">Сначала завершите верификацию.</div>`:state.quote.status==='none'||state.quote.status==='change'?btn(state.quote.status==='change'?'Создать новую версию КП':'Создать демо КП','createQuote()'):status('КП v'+state.quote.version+' отправлено','info')}</div></div>`}
function quotes(){return `<h1>КП и документы</h1><p class="sub">КП - версионируемый объект внутри платформы, а не вложение в письме.</p><div class="card"><table class="table"><tr><th>Объект</th><th>Версия</th><th>Статус</th></tr><tr><td>КП</td><td>${state.quote.version||'-'}</td><td>${state.quote.status==='accepted'?status('Принято','ok'):state.quote.status==='sent'?status('Отправлено','info'):state.quote.status==='change'?status('Корректировка','warn'):status('Нет')}</td></tr><tr><td>Договор</td><td>1</td><td>${state.contract==='signed'?status('Подписан','ok'):status('Нет')}</td></tr><tr><td>Счет</td><td>1</td><td>${state.invoice==='issued'?status('Выставлен','ok'):status('Нет')}</td></tr></table></div>`}
function execution(){return `<h1>Исполнение и исключения</h1><p class="sub">Marketplace формирует handoff и получает агрегированные статусы. Он не становится новым ЛИС.</p><div class="grid"><div class="card span6"><h2>Готовность</h2><table class="table"><tr><td>Оплата</td><td>${state.payment==='paid'?status('Подтверждена','ok'):status('Нет','warn')}</td></tr><tr><td>Список сотрудников</td><td>${state.roster==='ready'?status('Принят','ok'):status('Нет','warn')}</td></tr></table></div><div class="card span6"><h2>Execution order</h2>${state.execution.status==='none'?`<div class="mutedbox">Еще не передан.</div>`:`<div class="progress"><div style="width:${state.execution.progress}%"></div></div><div class="help">${state.execution.progress}%</div>`}</div><div class="card span12"><h2>Исключения</h2><div class="mutedbox">В демо исключений нет. В production здесь будут ошибки roster, недоступность выезда, платежные расхождения и другие отклонения.</div></div></div>`}
function audit(){return `<h1>Журнал действий</h1><p class="sub">P0 audit trail по организации и заказу.</p><div class="card">${state.activity.length?`<table class="table"><tr><th>Время</th><th>Событие</th></tr>${state.activity.map(a=>`<tr><td>${a.time}</td><td>${a.text}</td></tr>`).join('')}</table>`:`<div class="mutedbox">Событий пока нет.</div>`}</div>`}
function render(){document.getElementById('role-client').classList.toggle('active',state.role==='client');document.getElementById('role-dkp').classList.toggle('active',state.role==='dkp');document.getElementById('nav').innerHTML=nav();let html='',title='',sub='';if(state.role==='client'){sub='Клиентский кабинет';if(state.clientPage==='home'){html=home();title='Главная'}else if(state.clientPage==='catalog'){html=catalog();title='Каталог'}else if(state.clientPage==='organization'){html=organization();title='Организация'}else if(state.clientPage==='order'){html=order();title='Мой заказ'}else{html=documents();title='Документы'}}else{sub='Backoffice ДКП';if(state.dkpPage==='queue'){html=queue();title='Очередь ДКП'}else if(state.dkpPage==='case'){html=dkpCase();title='Карточка заказа'}else if(state.dkpPage==='quotes'){html=quotes();title='КП и документы'}else if(state.dkpPage==='execution'){html=execution();title='Исполнение'}else{html=audit();title='Журнал действий'}}document.getElementById('content').innerHTML=html;document.getElementById('page-title').textContent=title;document.getElementById('page-subtitle').textContent=sub;save()}
render();
